source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'UIImage-Categories', '~> 0.0.1'
pod 'AFNetworking', '~> 2.5'
pod 'Facebook-iOS-SDK', '~> 3.17'
pod 'SDWebImage', '~> 3.7'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'NSLogger-CocoaLumberjack-connector', '~> 1.3'
pod 'CocoaLumberjack', '~> 1.6.2'
pod 'NSLogger', '~> 1.1'
pod 'NewRelicAgent', '~> 3.324'
pod 'NSTimer-Blocks', '~> 0.0.1'
pod 'JASidePanels', '~> 1.3.2'
pod 'BButton'
pod 'DAKeyboardControl', '~> 2.2.0'
pod 'BSKeyboardControls', '~> 2.0'
pod 'SSZipArchive', '~> 0.3.1'
#pod 'FlurrySDK', '~> 5.0'
#pod 'SSToolkit', '~> 2.0'
#pod 'iRate', '~> 1.8'
pod 'TPKeyboardAvoiding', '~> 1.2'
pod 'IAPManager', '~> 0.2'
pod 'MRProgress', '~> 0.8'
pod 'CrashlyticsFramework', '~> 2.2'
pod 'Orbiter', '~> 2.0'
pod 'NSDate+TimeAgo', '~> 1.0'

target :fantasyfitnessTests, :exclusive => true do
	pod 'Kiwi'
	pod 'OHHTTPStubs', '~> 2.0.0'
end